[Feat/week1]  : 필수과제
NOW-SOPT-ANDROID/myeongseok_kim pull request #1
Opened 2024-04-02 14:45 UTC by cacaocoffee

## 🛠 Related issue
- 이슈등록을 까먹어서 컴포즈부터 다시해볼게요..!

## ✏️ Work Description
**로그인화면**
- [x]  ID,Password 입력 
    - [x] 검증단계

**회원가입**
- [x] ID, Password,nickname,MBTI 등 입력
- [x] 예외처리
   - [x]  ID : 6~10 글자
   - [x] Password : 8~12 글자
   - [x] 닉네임 : 한 글자 이상, 공백으로만 이루어진 닉네임은 불가

**메인화면**
- [x]  UI
- [x] 정보 표시

## 📸 Screenshot

https://github.com/NOW-SOPT-ANDROID/myeongseok_kim/assets/75840431/99a49f90-df57-42e1-89d3-8c90cbca2c3d

## 😅 Uncompleted Tasks

## 📢 To Reviewers
 첫 PR이라 부족한 점 많을 것 같아요. 많은 피드백 부탁드립니다.
data binding은 나중에 다녀와서 리팩토링 해보려구 넣기만 했어요

## ✅ Check List
- [x] Code/Git 컨벤션은 지켰나요?
- [x] PR올리기 전에 검토했나요?
- [x] 코드리뷰 반영했나요?

2024-04-02 14:52 UTC, chanubc commented on app/build.gradle
> +        dataBinding true
1주차에 dataBinding까지..

2024-04-02 14:52 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +    private var nickname = ""
변수명은 소문자로 해주세용!!

2024-04-02 14:58 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +        }
각각 함수로 분리하는 건 어떨까요?

initSignUpBtnClickListener()
initLoginBtnClickListener()

2024-04-02 15:18 UTC, chanubc requested changes
이렇게 짧은 시간안에 진짜 폼 미쳤네요ㄷㄷ
너무 잘 보고 갑니다!!
특히 함수화를 잘하시는 것 같아요. 

리뷰 몸상태가 안좋아서 어질어질한 상태에서 달았네요ㅋㅋㅋ
한번 읽어 주세요~ 고생많으셨습니다!

2024-04-02 15:18 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +                startActivity(intent)
```suggestion
    val intent = Intent(this, MainActivity::class.java).apply {
    putExtra("ID", ID)
    putExtra("password", password)
    putExtra("nickname", nickname)
    putExtra("MBTI", MBTI)
}
startActivity(intent)

```
이런식으로 scope함수로 묶어보는 건 어떨까요??

2024-04-02 15:18 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +                MBTI = result.data?.getStringExtra("MBTI") ?: ""
id password, mbti, nickname을 compaion object를 통해서 상수화를 시키면 메인 액티비티에서도 사용 가능 할 것 같습니다!!

2024-04-02 15:18 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +            Toast.makeText(this, "회원정보가 없습니다.", Toast.LENGTH_SHORT).show()
toast가 반복되는데 따로 함수화하는 건 어떨까요?

추후에 util의 확장함수로 만드는 방안도 있습니다!!

2024-04-02 15:18 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +            if (validateLogin()) {
함수화를 정말 잘하시네요!!

2024-04-02 15:18 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/MainActivity.kt
> +    private lateinit var nickname: String
이 부분 꼭 전역변수를 쓰지 않아도 될것 같아요!
init에서 초기화 시키고
layoutInit에 파라미터 값들을 넘기는 방안도 있을것 같습니다!!

2024-04-02 15:18 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +    }
우와 진짜 깔끔해요!!

2024-04-02 15:18 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/SignUpActivity.kt
> +        binding.btnLogin.setOnClickListener { if (validateSignUp()) signUpEvent() }
폼 미쳤다 ㄷㄷ 명석님 최고~~~~~~

2024-04-02 15:18 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/SignUpActivity.kt
> +        intent.putExtra("MBTI", binding.etSignupMBTI.text.toString())
요기도 scope함수로 묶을 수 있을것 같아요!

2024-04-02 15:18 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/SignUpActivity.kt
> +    }
이 부분 너무 좋네요! 저도 배우고 갑니다ㅎㅎ

2024-04-02 15:18 UTC, chanubc commented on app/src/main/java/com/sopt/now/util/BindingActivity.kt
> +}
어디까지 잘하시는 겁니까??

2024-04-02 15:18 UTC, chanubc commented on app/src/main/res/layout/activity_login.xml
> +
우와 GuideLine까지.. 진짜 최고에요!!

2024-04-02 15:18 UTC, chanubc commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/et_login_password"
자체 미미나 전이였을텐데.. 이미 컨밴션이 맞추어져 있군요ㅎㅎ

2024-04-02 15:18 UTC, chanubc commented on app/src/main/res/layout/activity_login.xml
> +            android:text="@string/login_welcome"
string추출까지.. 완벽합니다!!

2024-04-02 15:18 UTC, chanubc commented on app/src/main/res/values/strings.xml
> +    <!--공통요소-->
이런거 너무 좋아요!!
다른 분들도 string추출 후에 주석 달아주시면 좋을것 같아요!!

2024-04-02 15:33 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +        return true
toast가 반복되는데 따로 함수화하는 건 어떨까요?

추후에 util의 확장함수로 만드는 방안도 있습니다!!

2024-04-02 15:34 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/SignUpActivity.kt
> +        var text = binding.etSignupMBTI.text.length
혹시 얘네 들은 var인 이유가 있을까요..??

2024-04-02 15:35 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +                startActivity(intent)
각각 함수로 분리하는 건 어떨까요?

initSignUpBtnClickListener()
initLoginBtnClickListener()

2024-04-02 15:50 UTC, cacaocoffee commented on app/build.gradle
> +        dataBinding true
넣어보기만했어요!

2024-04-02 16:01 UTC, DoReMinWoo commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +                startActivity(intent)
변수별로 따로 전달을 해야할까요?? 객체로 전달하는 방법은 없을까요?

2024-04-03 01:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +            if (validateLogin()) {
하핳 감사합니다!

2024-04-03 01:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +    private var nickname = ""
넵 미처 놓쳤네요 ㅠㅜ 다음부턴 더 꼼꼼히 봐볼게요

2024-04-03 01:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/SignUpActivity.kt
> +        var text = binding.etSignupMBTI.text.length
아뇨 ㅠㅜㅠㅜ 신경 못썼네요 통일성이 부족하다니.. val 로 하면 더 좋은걸..

2024-04-03 01:12 UTC, cacaocoffee commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/et_login_password"
민우덕에 조금 배웠어요 ㅎㅎ

2024-04-03 01:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/util/BindingActivity.kt
> +}
모자라욬ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ감사합니다 덕분에 즐겁게 코딩해요

2024-04-03 01:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/SignUpActivity.kt
> +        intent.putExtra("MBTI", binding.etSignupMBTI.text.toString())
오... 미처 생각 못하고 있었네요! 감사합니다 스코프 함수는 종종 까먹게 되는거 같아요

2024-04-03 01:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/SignUpActivity.kt
> +        binding.btnLogin.setOnClickListener { if (validateSignUp()) signUpEvent() }
아닙니닿ㅎㅎㅎㅎㅎㅎㅎㅎ고마워요

2024-04-03 01:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/MainActivity.kt
> +    private lateinit var nickname: String
오 그렇네요 미처 생각 못하고있었어요 덕분에 참고해서 수정했습니다!

2024-04-03 01:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +                startActivity(intent)
scope 함수로 묶는 것도 처리했습니다! 
덕분에 @Parcelize 을  사용해서 해결했습니다.
과정속에서 Serializable ,Parcelable에 대해서도 알게되었구요. 
조만간 자료 정리해야겠어요
참고했던 자료는 아래와 같아요
[각각 용어에 대해](https://studyroadmap-kkm.tistory.com/167#Serializable-1)
[구현 엿보기](https://velog.io/@simsubeen/Kotlin-Parcelize-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-intent%EC%97%90-data-class-%EC%A0%84%EB%8B%AC%ED%95%98%EA%B8%B0#detailactivity)

2024-04-03 01:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +                startActivity(intent)
엇 덜쪼갰었네요 감사합니다!

2024-04-03 01:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +        return true
util로 뺴려구 찾아보며 시도하다가 시간관계상 여기까지.. 다음에 돌아와서 꼭 해볼게요!

2024-04-03 01:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +                MBTI = result.data?.getStringExtra("MBTI") ?: ""
오 확실히 compaion object 로 빼니까 재사용성이 높아졌어요

2024-04-03 01:12 UTC, cacaocoffee commented on app/src/main/res/layout/activity_login.xml
> +
고마워요!ㅎㅎㅎㅎㅎㅎ

2024-04-03 01:12 UTC, cacaocoffee commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/et_login_password"
민우 덕에 조금 배웠어요 ㅎㅎ

2024-04-03 01:14 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +                startActivity(intent)
login 이랑  singup쪽도 적용 가능할거 같은데 밤을 새서 그런가 머리가 안굴러가네요.. 다녀와서 해보겠습니다!

2024-04-03 08:05 UTC, KwakEuiJin reviewed
좋은 코드 잘보고 갑니다 명석님! 8주차 까지 화이팅ㅎㅎㅎ

2024-04-03 08:05 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +    }
apply는 함수 구조상 객체를 초기화 하고 반환하는 용도로 사용하는 것을 권장드립니다, 내부에서 동작까지 실행시키는 것은 추후에 다소 가독성 떨어지는 코드가 될 것 같아요

2024-04-03 08:05 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +        return true
validate라는 이름 답게 로그인 관련 검증 로직만 있으면 좋을 것 같습니다, Toast까지 띄워버리면 함수에서 이름 외에 동작이 실행되게 되니까요!

2024-04-03 08:05 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/MainActivity.kt
> +    }
함수명이 layout 자체를 init하는 건 아니기에 조금 다른 함수명이 좋을 것 같습니다, 하드코딩 부분도 문자열로 빼보면 좋을 것 같아요 ㅎㅎ

2024-04-03 08:05 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/MainActivity.kt
> +    }
class의 init 과 헷갈릴 수 있을 것 같습니다

2024-04-03 08:05 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/SignUpActivity.kt
> +        var text = binding.etSignupMBTI.text.length
val로 하면 뭐가 더 좋을까요?

2024-04-03 08:05 UTC, KwakEuiJin commented on app/build.gradle
> +        dataBinding true
데이터 바인딩은 지금 불필요할 것 같아요~!! 추후 프로젝트 설계시에는 오버엔지니어링이 되지 않도록 하는게 좋을 것 같습니다 ㅎㅎ

2024-04-03 08:05 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/data/User.kt
> +    var mbti: String?
각 변수가 nullable한 이유가 있을까요?!

2024-04-04 11:27 UTC, chanubc approved these changes

2024-04-05 02:03 UTC, OliviaYJH approved these changes
멋진 코드 잘 보고 가요!! 수고하셨습니다😊

2024-04-05 02:03 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +    private var nickname = ""
User data class가 있으니까 id, password, mbti, nickname 변수를 따로 생성하지 않고 User을 사용하는 건 어떨까요??

2024-04-05 02:03 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/ui/SignUpActivity.kt
> +        const val TAG_MBTI = "mbti"
LoginActivity에도 같은 내용이 companion object로 되어 있어서 그거 사용해도 좋을 것 같아요!

2024-04-07 13:33 UTC, hyoeunjoo reviewed
아직 코드를 100% 이해하지는 못했네요
그냥 남길 수 있는 최대한으로 남겨봤습니다..ㅎㅎ
점점 더 많은 코리를 달아보겠습니다 잘 보고 가요!

2024-04-07 13:33 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/data/User.kt
> +    var mbti: String?
data class가 이거군요..? 저도 배워서 꼭 해봐야겠습니다

2024-04-07 13:33 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +    }
이렇게 쓰면 훨씬 간결하게 쓸 수 있겠네요.. 배워갑니다

2024-04-07 13:33 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/ui/SignUpActivity.kt
> +    }
오 여기는 혹시 text !in 6..10 으로 써도 되는 곳일까요?

2024-04-10 17:13 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/SignUpActivity.kt
> +    }
네 맞아요 상수화 작업까지 해서 수정해보겠습니다!

2024-04-11 04:17 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +    }
피드백 감사합니다.
```kotlin
val intent = Intent(this, SignUpActivity::class.java)
with(intent){
  //~~중략~~
  resultLauncher.launch(this)
}
```
위처럼 분리하면 
동작의 분리가 코드상에서 이루어져 가독성 향상이 될거 같네요

2024-04-11 08:44 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/SignUpActivity.kt
> +        var text = binding.etSignupMBTI.text.length
질문 감사합니다. 한번 생각해볼수 있었네요.  
가변성은 그 자체로 비용이기에 불필요한 가변성을 허용하지 않는 것이 좋다고 알고 있어요
그렇기에 가변성 제한을 주기 때문에 val 을 사용하는것이 좀 더 바람직해보여요

### 가변성은 왜 제한을 해야하는가?
시간의 변화에 따라 변하는 요소를 표현하는 것은 유용하다.
하지만, 상태를 적절하게 관리하는 것은 생각보다 어렵다.

- **디버깅**의 어려움
    
    ( 상태 변경이 많을 경우 추적이 힘들고, 이해하기도 어렵다.)
    
- **코드 실행 추론**의 어려움
    
    ( 시점에 따라 값이 변경되어 현재의 값을 알아야 실행을 예측할 수 있다.)
    
- 멀디스레드 프로그램일 경우 **변경이 일어나는 모든 부분에서 충돌** 가능
- **테스트**의 어려움 ( 모든 상태를 테스트해야 한다. )

나름대로 조사해보았는데 틀린 부분있으면 알려주시면 감사하겠습니다!

2024-04-11 08:44 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/SignUpActivity.kt
> +        const val TAG_MBTI = "mbti"
그렇네요 재활용성 높이게 해당 방식으로 수정했어요! 감사합니다!

2024-04-11 08:44 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/data/User.kt
> +    var mbti: String?
parcelize 사용하면서 미숙한 사용을 했던것 같습니다. 수정했어요! 꼼꼼히 봐주셔서 감사합니다.

2024-04-11 08:44 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +        return true
넵 수정했습니다! 그런데 각각 함수화하고 toast 를 require 구문 으로 바꿔 넣었는데 이 방법 말고 아예 분리하는 다른 방법이 있을지 고민하게되네요

2024-04-11 08:44 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/MainActivity.kt
> +    }
넵 감사합니다 반영해서 수정했어요

2024-04-11 23:53 UTC, chanubc commented
머지하셔도 됩니다!!

2024-04-14 09:49 UTC, merged

2024-04-16 04:43 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/LoginActivity.kt
> +    }
``` kotlin
 private fun initSignUpBtnClickListener() {
        val intent = Intent(this, SignUpActivity::class.java)
        resultLauncher.launch(intent)
        
        // 혹은
        Intent(this, SignUpActivity::class.java).apply {
            // 중략
        }.let { intent ->
            resultLauncher.launch(intent)
        }
    }
```

2024-04-16 04:43 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/SignUpActivity.kt
> +    }
오 내부에서 require처리가 아닌 차라리 Boolean으로 받아서 false시에 해당하는 에러 메시지를 띄우는 방식을 검토해보시는게 어떠신지 물어본 것이였습니다 ㅎㅎ

혹은 함수명에 AndShowErrorToast를 붙여도 될 것 같아요 (다만 함수가 너무 많은 일을 하게 되면 유지보수할 때 어려워질수도?!)