[4주차] xml 과제 완료
NOW-SOPT-ANDROID/myeongseok_kim pull request #11
Opened 2024-05-03 08:54 UTC by cacaocoffee

## 🛠 Related issue
- #10 

## ✏️ Work Description
- [x] 회원가입 서버 통신
- [x] 로그인 서버 통신
- [x] 정보 불러오기 통신

## 📸 Screenshot

https://github.com/NOW-SOPT-ANDROID/myeongseok_kim/assets/75840431/dcbeb851-41cc-4f8a-8a16-dd27c2590a7a

## 😅 Uncompleted Tasks
- 선택과제 
    - [ ] 비밀번호 변경
    - [ ] HomeFragment 와 Open API 연결하기

## 📢 To Reviewers
 authService 에 3개로 분리한 서비스로직을 다 넣는게 좋을지 고민됩니다! 잘부탁드려요

## ✅ Check List
- [x] Code/Git 컨벤션은 지켰나요?
- [x] PR올리기 전에 검토했나요?
- [ ] 코드리뷰 반영했나요?

2024-05-05 08:12 UTC, librarywon commented
안녕하세요 명석님 반갑습니다 😄 저는 32,33기 안드로이드를 수료한 명예 OB 서재원이라고합니다.

영광스럽게도 명석님 리뷰어를 맡게 되었는데 제가 생각하는 코드리뷰는 "상호 의견을 나누면서 서로 성장하는 것"이라고 생각해요!

제가 아는 선에서 최대한 의견을 제시볼테니 제 의견이 무조건 맞지 않다는 것을 염두하고 리뷰를 확인해주시면 좋을 것 같습니다

과제 하느라 수고하셨습니다

2024-05-05 08:55 UTC, librarywon commented on app/src/main/AndroidManifest.xml
> +            android:exported="false"></activity>
`</activity>`는 제거해주셔도 무방할 것 같습니다.

2024-05-05 08:55 UTC, librarywon commented on app/src/main/java/com/sopt/now/data/Profile.kt
>  package com.sopt.now.data
data layer에서 사용하시는 모델들을 data패키지 최상위에 배치하셨군요

data/model이라는 패키지를 생성해서 그 아래 배치하는 것은 어떻게 생각하시나요?

2024-05-05 08:55 UTC, librarywon commented on app/src/main/java/com/sopt/now/data/data/AuthService.kt
> +package com.sopt.now.data.data
data 패키지 속 data패키지는 조금 혼동의 여지가 있어보이는데 
아래 파일들의 특징을 잘 나타낼 수 있는 이름으로 변경하시는 것을 추천드립니다.

2024-05-05 08:55 UTC, librarywon commented on app/src/main/java/com/sopt/now/data/User.kt
> +    var userid: String = "",
기본값을 배정한 변수와 아닌 변수를 따로 두신 이유가 있을까요?
그리고 변수가 카멜케이스 규칙을 따르지 않은 것 처럼 보입니다.

2024-05-05 08:55 UTC, librarywon commented on app/src/main/java/com/sopt/now/data/data/InfoService.kt
> +        @Header("memberid") userId: String?,
userId가 nullable한 `string?`자료형을 가지고 있네요
해당 함수를 호출 할 때 인자로 null 값이 넘어올 가능성이 있나요? 만약 넘어온다면 어떻게 처리를 해야할까요?
위의 고민들을 해보시면 어떻게 코드를 작성할지 도움이 되실 것 같습니다!

2024-05-05 08:55 UTC, librarywon commented on app/src/main/java/com/sopt/now/ui/login/LoginActivity.kt
>      private fun setResultNext() {
이 함수 이름만 보고서는 registerForActivityResult의 세팅을 하는것으로 보이지 않는 것 같습니다.

우리가 함수 네이밍을 중요하게 여기는 이유는 뭘까요? [Clean Code]에서는 의미 있는 이름과 함수를 강조합니다. 해당 책에서 여러 규칙을 제시하니 참고해보시면 좋을 것 같네요

저는 다른 사람들이 함수 이름만 보고서 어떤 역할을 수행하고 어디에 영향을 미칠지 알 수 있는 이름이 의미 있는 이름이라고 생각합니다. 내가 혹은 우리 그룹만 아는 축약어를 사용하는 것 보다 50글자 함수이름이 더 좋다고 생각합니다.

너무 함수 이름을 길게 작성하는데 두려움을 없애시면 좋을 것 같네요

2024-05-05 08:55 UTC, librarywon commented on app/src/main/java/com/sopt/now/ui/login/LoginActivity.kt
> +    private fun initButton() {
이 함수는 어떤 버튼을 초기화하는 것인가요?

객체지향 1원칙 단일책임원칙을 함수에도 적용 가능한데요 `하나의 함수가 하나의 일`을 수행하면 된다는 뜻입니다. 

이 함수는 하나의 일을 수행하고 있을까요?

2024-05-05 08:55 UTC, librarywon commented on app/src/main/java/com/sopt/now/ui/login/LoginActivity.kt
> +    private fun initObserver() {
나중에 코드를 작성하시다 보면 여러 `liveData` 변수를 observe하는 코드를 작성하실 수 있습니다.
그 때도 이러한 함수 이름을 유지해야할까요?

2024-05-05 08:55 UTC, librarywon commented on app/src/main/java/com/sopt/now/util/UiState.kt
> +}
`uiState`를 util에 생성하고 범용적으로 사용하실려고 했던 것 같은데 재사용성에 강점이 있을수도 있지만 제가 생각하는 단점을 말해보겠습니다.

모든 상황에서 UiState를 사용하려고 하면 특정 UI 컴포넌트나 기능에 필요한 세부적인 상태 관리 요구사항을 만족시키지 못할 수 있습니다. 예를 들어, 특정 UI 요소에서는 추가적인 상태 정보가 필요할 수 있으나, UiState가 이를 제공하지 않을 경우 별도의 상태 관리 로직을 추가로 구현해야 할 수 있습니다.

uiState가 특정 데이터 타입이나 UI 요소에 최적화되지 않았기 때문에, 시간이 지나면서 앱의 요구사항이 복잡해질 때 이를 확장하거나 수정하기 어려울 수 있습니다. 오히려 유지보수가 더 어려워질 수 있는 것이죠

2024-05-05 08:55 UTC, librarywon commented on app/src/main/java/com/sopt/now/ui/login/LoginActivity.kt
> +import com.sopt.now.data.datasouce.RequestLoginDto
우리가 레이어 분리를 하는 목적은 무엇일까요?
data-ui 레이어를 분리하였지만 여전히 data의 의존성을 가지고 있는 상황입니다.
예를 들어 서버에서 내려주는 변수명에 변경이 생긴다면 어떤 문제상황이 발생할지 예측해보면 좋을 것 같습니다.

2024-05-05 08:55 UTC, librarywon commented on app/src/main/java/com/sopt/now/ui/login/LoginViewModel.kt
> +    val liveData = MutableLiveData<UiState<User>>()
코틀린에는 이미 `LiveData`라는 클래스가 존재합니다 이미 존재하는 이름과 동일한 이름을 사용하는 것은 지양하는 것이 좋은 것 같습니다.

더 목적에 맞게 변경해보시는 것은 어떨까요?

2024-05-05 08:55 UTC, librarywon commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
> +                }
UiState에 loading을 두신 이유는 무엇인가요?
만약 로딩이 필요 없는 화면이라면 보일러플레이트 코드가 될 수 있겠네요

2024-05-05 08:55 UTC, librarywon commented on app/src/main/java/com/sopt/now/ui/main/home/MainHomeAdapter.kt
> +    override fun getItemCount(): Int = userList.size
ListAdapter는 getItemCount() 함수를 선언해줄 필요가 없답니다. 혹시 필요로 하여서 사용하셨을까요?

2024-05-05 08:55 UTC, librarywon commented on app/src/main/java/com/sopt/now/ui/main/home/MainHomeMeViewHolder.kt
> +    fun onBind(userData: Profile) {
여기도 view에서 data model인 `Profile`에 의존을 하고 있군요

2024-05-05 08:55 UTC, librarywon commented on app/src/main/java/com/sopt/now/ui/signup/SignUpActivity.kt
> +        )
```suggestion
        return RequestSignUpDto(
            authenticationId = binding.etSignupId.text.toString(),
            password = binding.etSignupPassword.text.toString(),
            nickname = binding.etSignupNickname.text.toString(),
            phone = binding.etSignupNumbers.text.toString()
        )
```
이렇게 불필요한 변수 선언 없이 사용할 수 있겠다는 생각도 듭니다!

2024-05-05 10:56 UTC, OliviaYJH approved these changes
수고하셨습니다!

2024-05-05 10:56 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/ui/login/LoginViewModel.kt
> +                    Log.d("test_loginservice", "onResponse: ${response.body()}")
불필요한 테스트 로그는 삭제해도 좋을 것 같아요!

2024-05-05 10:56 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/ui/login/LoginActivity.kt
> +                is UiState.Loading -> {
Loading 상태에는 무슨 일을 하나요?

2024-05-05 10:56 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/ui/login/LoginViewModel.kt
> +                        liveData.value = UiState.Error("로그인 실패  에러 메시지 파싱 실패")
스트링 값으로 빼도 좋을 것 같아요!

2024-05-05 13:14 UTC, chanubc requested changes
서버통신 어려우셨을텐데 고생 많으셨습니다!
점점 실력이 느네요!

2024-05-05 13:14 UTC, chanubc commented on app/src/main/java/com/sopt/now/data/ApiFactory.kt
> +}
```suggestion
object ServicePool {
    val authService: AuthService by lazy { create<AuthService>() }
    val loginService: AuthService by lazy { create<LoginService>() }
    val infoService: InfoService by lazy { create<InfoService>() }
}
```

이러면 서비스 중 하나만 사용되어도 ServicePool 객체가 참조될 때 나머지 서비스들도 모두 초기화되는 문제가 있습니다! 불필요한 리소스를 유발 할 것 같아요.

특히 네트워크 관련 서비스의 경우 초기화 과정에서 추가적인 시간이 소요될 수 있으므로 비효율적 일 수도 있을 것 같습니다!

2024-05-05 13:14 UTC, chanubc commented on app/src/main/java/com/sopt/now/data/data/LoginService.kt
> +}
관심사에 따라 앞에 AuthSerivce안에 작성해도 될 것 같습니다!
따로 interface를 만드신 이유가 있을까요?

2024-05-05 13:14 UTC, chanubc commented on app/src/main/java/com/sopt/now/data/datasouce/ResponseLoginDto.kt
> +)
반복 되는 response는 BaseResopnse 만들어서 관리하는 법도 있습니다.
반복되는 dto들은 BaseResponse로 따로 만드는 방법도 있습니다!
```kotlin
@Serializable
data class BaseResponse<T>(
    @SerialName("code")
    val code: Int,
    @SerialName("message")
    val message: String,
    @SerialName("data")
    val data: T? = null
)
```
이런식으로요!

2024-05-05 13:14 UTC, chanubc commented on app/src/main/java/com/sopt/now/data/datasouce/ResponseLoginDto.kt
> +)
```kotlin
    @POST("$MEMBER/$LOGIN")
    suspend fun login(
        @Body request: RequestLoginDto
    ): Response<BaseResponse<Unit>>
```
로그인의 경우 전 이런식으로 사용했습니다!

2024-05-05 13:14 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/login/LoginActivity.kt
> +                is UiState.Loading -> {
```suggestion
                is UiState.Loading -> Unit
```
따로 상태를 설정한게 없다면 Unit으로 작성해도 됩니다

2024-05-05 13:14 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/login/LoginActivity.kt
> +                }
```suggestion
                is UiState.Success -> navToHome(state.data)
                is UiState.Error -> toast(state.errorMessage)
```
사실 상관없는데 이게 가독성이 더 좋아보여요! 상관은 없습니다

2024-05-05 13:14 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/login/LoginActivity.kt
> +            startActivity(this)
```suggestion
        Intent(this, MainActivity::class.java).apply {
             putExtra(TAG_USER, user)
        }
        startActivity(intent)
```

scope함수 사용할때 차이점을 알고 사용하는게 좋을 것 같습니다!

startActivity는 Intent 객체를 사용하는 Context의 함수입니다. 따라서 startActivity(this)를 호출하려면 this가 Context를 가리키도록 해야 합니다. 하지만 with 스코프 내에서 this는 Intent 객체를 참조합니다. 따라서 startActivity(this) 사용이 올바르지 않을 것 같습니다!

2024-05-05 13:14 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/login/LoginViewModel.kt
> +    val liveData = MutableLiveData<UiState<User>>()
baking property 적용해주세요!
[backing property](https://yoon-dailylife.tistory.com/45)
지금은 외부에서도 MutableLiveData의 값을 변경이 가능 합니다.

2024-05-05 13:14 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/login/LoginViewModel.kt
> +                        liveData.value = UiState.Error(errorMessage)
```suggestion
         liveData.postValue(UiState.Error(errorMessage))
```

2024-05-05 13:14 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/main/MainViewModel.kt
> +
요기도 위에 리뷰와 같아요!

2024-05-05 13:14 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/main/home/MainHomeAdapter.kt
> +    override fun getItemCount(): Int = userList.size
```suggestion
    override fun getItemCount(): Int = currentList.size
```
그리고 만약 필요로 한다면 이런식으로 사용하셔야 합니다!

2024-05-05 13:14 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/signup/SignUpViewModel.kt
> +    val liveData = MutableLiveData<UiState<User>>()
backing property적용해주세요!

2024-05-05 13:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/login/LoginActivity.kt
> +            startActivity(this)
음 이렇게 보니까 한줄짜리라 굳이 scope안써도 될것 같네요!

2024-05-05 14:40 UTC, hyoeunjoo approved these changes
과제하느냐 수고 많으셨습니다 오늘도 좋은 코드 보고가네요 ㅎㅎ
이미 많이 다들 남겨주셔서 제가 남길게 더더더욱 없어졌네요.. 성의없는건 아니니 오해 말아주세요ㅜㅜ 열심히 읽고 배워갑니다~

2024-05-05 14:40 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/ui/main/MainViewModel.kt
> +            }
저도 스트링 값으로 추출 못했는데 나중에 같이 리팩하면서 해요 ㅎㅎ

2024-05-05 14:40 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/ui/signup/SignUpActivity.kt
> +                is UiState.Loading -> {
요 부분은 signUpObserver로 바꾸셔서 여러군데에 있는 observer들을 구분할 수 있게 해주시는건 어떤가요??

2024-05-06 02:29 UTC, cacaocoffee commented
> 안녕하세요 명석님 반갑습니다 😄 저는 32,33기 안드로이드를 수료한 명예 OB 서재원이라고합니다.
> 
> 영광스럽게도 명석님 리뷰어를 맡게 되었는데 제가 생각하는 코드리뷰는 "상호 의견을 나누면서 서로 성장하는 것"이라고 생각해요!
> 
> 제가 아는 선에서 최대한 의견을 제시볼테니 제 의견이 무조건 맞지 않다는 것을 염두하고 리뷰를 확인해주시면 좋을 것 같습니다
> 
> 과제 하느라 수고하셨습니다



안녕하세요 재원님 34기 YB 김명석입니다! 바쁘신 와중에도 제 코드에 섬세한 리뷰달아 주셔서 감사합니다.  
이번 리뷰를 통해 좀 더 공부하고 찾아볼 것들을 알게되었습니다. 
다른 팀원 코드리뷰도 보며 공부 더 해볼게요. 다시 한번 귀중한 시간 내어 주셔서 감사합니다!

2024-05-08 17:12 UTC, cacaocoffee reviewed
많은 리뷰 주셔서 감사합니다! 덕분에 많이 생각할 거리를 얻을 수 있었어요!

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/AndroidManifest.xml
> +            android:exported="false"></activity>
넵! 제거했습니다 꼼꼼히 봐주셔서 감사해요

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/data/ApiFactory.kt
> +}
생각 못하고 있던 부분이었는데 감사합니다!

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/data/Profile.kt
>  package com.sopt.now.data
안그래도 디렉토리 구조를 어떻게 짜야할지 고민하고 있었는데 감사합니다! 어렵네요 ㅜㅠ

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/data/User.kt
> +    var userid: String = "",
userid를 추가하면서 초기값을 할당했는데요 
userid가 로그인 과정에서 받은 userid 값을 메인 화면으로 넘겨줄 때 사용되는데 이외엔 사용이 안되기에 넣었습니다.
저번주 코드가 id,password nickname mbti 가 모두 필수로 필요했어서 초기값을 할당하지 않았었습니다.

위에 방식보다 더 깔끔한 방식이 있을 거 같은데 잘모르겠네요... sharedPreference를 사용해볼까합니다.

카멜 케이스는 신경 못썼던거 같네요! 수정했어요!

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/data/data/InfoService.kt
> +        @Header("memberid") userId: String?,
호출할때 인자로 null이 올 가능성은 없습니다!
코드를 잘못 짰네요... 좀 더 꼼꼼히 봐볼게요 

nullable 하지 않은 값들을 최대한 사용하려고 해봐야겠어요

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/data/data/LoginService.kt
> +}
사실 따로 interface를 usecase 처럼 생각해서 분리해야하나 고민을 했었어요...
AuthService라는 곳에 인증 로그인 등에 대한 정보가 하나로 있는게 좋아보이네요

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/data/datasouce/ResponseLoginDto.kt
> +)
안그래도 반복되는 건데 어떻게 하나로 못 묶나 고민하는데 감사합니다! 바로 적용해볼게요!

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/login/LoginActivity.kt
> +import com.sopt.now.data.datasouce.RequestLoginDto
비즈니스 로직과 Ui에 관한 코드를 분리하여 관리와 유지 보수 측면에 도움이 되기 위해서 라고 생각해요

클린아키텍처를 적용하여 domain 을 두어 중간을 분리하면 
변수명 변경에 따라서 유지보수에 도움이 될 거 같네요

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/data/data/AuthService.kt
> +package com.sopt.now.data.data
넵 패키지 이름 변경해봤어요! 제대로 한지는 모르겠네요...

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/login/LoginActivity.kt
> +                is UiState.Loading -> {
감사합니다! 아직 Uistate 활용법이 익숙하지 않네요..
비워두고 나중에 스켈레톤 UI 띄우는 코드가 필요한가 하고 고민했었네요

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/login/LoginActivity.kt
> +    private fun initButton() {
버튼들을 초기화 시켜주는 걸 묶는다고 생각해서 하나의 일을 수행하고 있다고 생각했는데 좀 더 생각해보니 bind.~ 까지 다른 함수에 위임해줘도 되겠네요! 수정했습니다 감사해요!

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/login/LoginActivity.kt
> +    private fun initObserver() {
엑티비티 별로 각 state에 맞는 이름으로 변경했어요! 미처 생각 못했는데 감사합니다.

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/login/LoginActivity.kt
> +                }
엇 맞네요 한줄인데! 변경했습니다 감사해요!

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/login/LoginActivity.kt
> +            startActivity(this)
scope 함수 아직 너무 어려운거 같아요.. 
this가 Context를 가리키도록 해야하는지 몰랐어요.. 감사합니다 어렵네요

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/login/LoginViewModel.kt
> +    val liveData = MutableLiveData<UiState<User>>()
목적에 맞게 state라는 이름을 붙이며 이름 변경을 했습니다. 
또한 baking property 적용 했습니다!
감사해요!

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/login/LoginViewModel.kt
> +                    Log.d("test_loginservice", "onResponse: ${response.body()}")
엇 다지운줄알았는데 남아있었네요 감사합니다!

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
> +                }
저때는 UIstate를 잘몰랐어서, 
스켈레톤 UI 띄우거나 할 때 사용하지 않을까 하고 넣었는데 고민이되네요

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/login/LoginViewModel.kt
> +                        liveData.value = UiState.Error("로그인 실패  에러 메시지 파싱 실패")
넵 keyStroage만들어서 분리해뒀어요 xml과 UI 쪽에 보이는건 string 에 빼고 코드상에서 사용되는 건 따로 분리해두려고요

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/main/MainViewModel.kt
> +            }
넿ㅎㅎㅎ 추출했나요?

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/main/home/MainHomeAdapter.kt
> +    override fun getItemCount(): Int = userList.size
아뇨 리사이클러뷰 어뎁터에서 수정하는 과정에 놓친 거 같습니다 감사해요!

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/main/home/MainHomeMeViewHolder.kt
> +    fun onBind(userData: Profile) {
추후 도메인으로 분리해보겠습니다..!

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/signup/SignUpActivity.kt
> +                is UiState.Loading -> {
이름 변경했습니다! 너무 같은 이름들을 사용하고 네이밍에 문제가 많았네요 ㅠ

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/signup/SignUpActivity.kt
> +        )
오.. 덕분에 아래와 같이 수정했습니다 감사합니다
![image](https://github.com/NOW-SOPT-ANDROID/myeongseok_kim/assets/75840431/6f1cf1a0-bbaa-4ab2-b5a7-c6fb13992828)

2024-05-08 17:12 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/util/UiState.kt
> +}
이번 과제를 하면서  uistate를 공부해봐서 미숙한 점이 많습니다.

위같은 단점이 있을 수 있군요.. 각 화면에 맞는 uiState를 만들면 너무 파일이 많아 질까 걱정되어 범용적으로 사용하려고해봤습니다. 

몇번 커스텀하면서 쓰다보니 위에 말씀하신 대로 각 로직에 따라 수정하기 힘들다는게 느껴지더라구요 각 로직에 따라 생성한다면 코드의 위치는 어떻게 해야할지도 고민입니다..

2024-05-09 01:30 UTC, librarywon commented on app/src/main/java/com/sopt/now/ui/login/LoginActivity.kt
> +import com.sopt.now.data.datasouce.RequestLoginDto
음 클린아키텍처도 좋지만 제 질문의 의도와 조금 차이가 있네요 
ui 레이어에서 사용하는 모델을 data레이어의 모델을 가져다 쓰는중인데 다른방법은 없을까요?

2024-05-09 01:32 UTC, librarywon commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
> +                }
스켈레톤 로딩이나 로딩화면을 보여준다면 필요하다고 생각합니다!

2024-05-09 01:34 UTC, librarywon commented on app/src/main/java/com/sopt/now/ui/main/home/MainHomeMeViewHolder.kt
> +    fun onBind(userData: Profile) {
구글 권장 아키텍처에서는 도메인이 옵셔널인 것 처럼 반드시 도메인이 필요하지는 않습니다

무엇이 도메인인지 정의를 잘 알고 레이어 분리를 고민해보시는 것도 좋을 것 같습니다

2024-05-09 08:46 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/main/home/MainHomeMeViewHolder.kt
> +    fun onBind(userData: Profile) {
어렵네요 ㅠㅜ 답변감사합니다 공부해서 적용해볼게요!

2024-05-24 04:17 UTC, merged