[Feat/week2] : 필수과제
NOW-SOPT-ANDROID/myeongseok_kim pull request #5
Opened 2024-04-17 19:43 UTC by cacaocoffee

## 🛠 Related issue
- closed #4 

## ✏️ Work Description
- [x] Home
       - [x] 리스트 상단에  Friend와 다른 프로필 화면
- [x] 바텀네비게이션으로 프래그먼트 전환

## 📸 Screenshot

https://github.com/NOW-SOPT-ANDROID/myeongseok_kim/assets/75840431/247bc193-1cca-4d9e-ab9f-dfbc0192c494

## 😅 Uncompleted Tasks

## 📢 To Reviewers
멀티뷰 타입을 위해 Profile로 데이터 클래스를 분리했습니다.
viewmodel 쪽에 userData로 목록을 친구와 자신의 프로필 불러오고
myProfile 을 통해서 프로필 화면에 적용했습니다.

잘부탁드려요! 

## ✅ Check List
- [x] Code/Git 컨벤션은 지켰나요?
- [x] PR올리기 전에 검토했나요?
- [ ] 코드리뷰 반영했나요?

2024-04-20 11:40 UTC, jihyunniiii reviewed
코드가 진짜 깔끔하시네요! 고생하셨습니다 ~

2024-04-20 11:40 UTC, jihyunniiii commented on app/src/main/java/com/sopt/now/ui/main/home/MainHomeAdapter.kt
> +    RecyclerView.Adapter<RecyclerView.ViewHolder>() {
LIstAdapter 사용해 보세요 !

2024-04-20 11:40 UTC, jihyunniiii commented on app/src/main/java/com/sopt/now/ui/main/profile/MainProfileFragment.kt
> +    }
개인적으로,, 뷰에 뜨는 텍스트 들은 strings.xml에서 한 번에 관리하는 게 좋아 보여요!
companion object 내부에서는 뷰에 뜨지 않는 값 중 상수화 하는 값만 넣는 게 좋을 것 같습니다.

2024-04-20 11:40 UTC, jihyunniiii commented on app/src/main/res/layout/item_home_feed_me.xml
> +        android:layout_height="100dp"
```suggestion
        android:layout_width="100dp"
        android:layout_height="0dp"
        app:layout_constraintDimensionRatio="1"
```

2024-04-20 13:10 UTC, Eonji-sw reviewed
activity_sign_up.xml 62 line 오타난거 보고 왔어염 ㅋ.ㅋ 코리는 나중에...

2024-04-21 06:41 UTC, OliviaYJH approved these changes
수고하셨습니다😊

2024-04-21 06:41 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/util/BindingFragment.kt
> +    }
onDestroyView에서 binding을 해제시켜주는 코드 추가하면 좋을 것 같아요!

2024-04-21 06:41 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/ui/main/MainViewModel.kt
> +                Profile.frilendsProfile("곽의진", "CUTE"),//자기소개에서 발췌
발췌했다고 주석 안달아도 CUTE인신거 다 알아요😁

2024-04-21 12:02 UTC, chanubc requested changes
어려웠을 텐데 고생많으셨습니다!
수정사항들 수정 반영해주세요

2024-04-21 12:02 UTC, chanubc commented on app/src/main/java/com/sopt/now/data/Profile.kt
> +    ):Profile()
같은 구조의 data class라면 sealed class로 따로 구현하는 의미가 없는 것 같습니다! 두 data class의 구조를 다르게 가거나 하나로 합치는 것이 나을 것 같아요

2024-04-21 12:02 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
> +        inputData()
inputData보다는 getUserData과 같이 변경하는 것이 함수 기능에 적합해 보입니다!

2024-04-21 12:02 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/main/home/MainHomeAdapter.kt
> +class MainHomeAdapter(context: Context) :
context를 파라미터로 받는 것과 내부에서 parent.context로 접근하는 것은 어떤 차이가 있는지 공부 해보시기 바랍니다!

2024-04-21 12:02 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/main/home/MainHomeAdapter.kt
> +        notifyDataSetChanged()
notifyDataSetChanged() 의 단점으로는 어떠한 부분이 있고
이것을 대체 하기 위한 것들이 무엇인지 알아보시면 좋겠습니다!

2024-04-21 12:02 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/main/MainViewModel.kt
> +                Profile.myProfile(_myProfile.value!!.nickname, _myProfile.value!!.mbti),
!! 타입은 지양합시다

2024-04-21 12:02 UTC, chanubc commented on app/src/main/java/com/sopt/now/ui/main/home/MainHomeFragment.kt
> +    }
observe와 set이 한 함수안에 포함되어 있기에 분리해야 된다고 봅니다!

2024-04-21 12:02 UTC, chanubc commented on app/src/main/java/com/sopt/now/util/BindingFragment.kt
> +    }
오우 날카로운 리뷰입니다!

2024-04-21 12:02 UTC, chanubc commented on app/src/main/res/layout/activity_main.xml
> +        <FrameLayout
```suggestion
        <androidx.fragment.app.FragmentContainerView
```
이게 더 적합해 보입니다!

2024-04-21 12:57 UTC, hyoeunjoo approved these changes
가독성이 높은 코드 잘 보구 갑니닷!! 
과제하느냐고 고생 많으셨어요~

2024-04-21 12:57 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/ui/main/home/MainHomeAdapter.kt
> +    }
보기 너무 편하고 좋네요..

2024-04-21 12:57 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/ui/main/home/MainHomeFragment.kt
> +
함수로 다 빼놓으니까 가독성 미쳤습니닷 
리팩할 때 이렇게 해야겠어요

2024-04-29 13:11 UTC, chanubc approved these changes
머지하시고 안된부분은 다음과제에서 반영해주세요~

2024-04-30 06:47 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/main/MainViewModel.kt
> +                Profile.myProfile(_myProfile.value!!.nickname, _myProfile.value!!.mbti),
넵!
 Profile.info(name = _myProfile.value?.nickname ?:"", mbti = _myProfile.value?.mbti ?:""),
 우선 위와 같이 변경했어요
 
 
 찾아보니까 MutableLiveData 가 .java로 되어 있더라구요. 
아래 블로그의 방식대로 수정도 했다가 나중에 flow로 바꾸려고 다시 위처럼 두었습니다.
   
   https://danggai.github.io/android/Kotlin%EC%97%90%EC%84%9C-MutableLiveData-Null-%EC%82%AC%EC%9A%A9-%EC%A0%9C%ED%95%9C/

2024-04-30 06:47 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/main/home/MainHomeAdapter.kt
> +    RecyclerView.Adapter<RecyclerView.ViewHolder>() {
덕분에 ListAdapter에 대해서 잘알게 되었어요! 감사합니다.

2024-04-30 06:47 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/main/home/MainHomeAdapter.kt
> +        notifyDataSetChanged()
notifyDataSetChanged()의 단점으로는 
바뀐 부분이 아니라 전체를 다시 갱신해야해서 연산처리 면에서 비효율적이라는 것을 알게되었습니다.


# 대체방법

## DiffUtil

DiffUtil은 이전 데이터 상태와 현재 데이터간의 상태 차이를 계산해서 반드시 업데이트해야 할 최소한의 

데이터만 갱신 시키기에 이를 사용하여 불필요한 리소스를 줄이기

## AsyncListDiffer.
 DiffUtil의 경우 아이템 개수가 많으면 비교연산에 필요한 시간이 길어질 수 있기 때문에 백그라운드 스레드에서 처리되어야 합니다. 
AsyncListDiffer 는 DiffUtil을 편하게 쓰기 위해서 만들어진 클래스로, DiffUtil에 대해 자체적으로 스레드 처리를 해 줍니다.

 ListAdapter는 내부적으로 AsyncListDiffer를 사용하여 백그라운드 스레드에서 효율적으로 목록의 차이를 계산하고 애니메이션을 자동으로 처리할 수 있음 

## 리사이클러뷰 어뎁터 고수되기

notifyItemChanged , notifyItemRangeChanged ,notifyItemInserted 등 
내부적으로 mObservable 가 어떻게 돌아가는 지 파악하여 상황에 맞는 로직구현  

-> 단점으로는 구현시간이 오래걸리지 않을까합니다.


이에 따라 ListAdapter 를 통해 변경해보려구해요

2024-04-30 06:47 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/main/home/MainHomeFragment.kt
> +    }
엇 그렇네요 함수 더쪼개보도록 해볼게요 감사합니다.

2024-04-30 06:47 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/util/BindingFragment.kt
> +    }
우와... 메모리누수는 생각도 못했네요 감사합니다!

2024-04-30 06:47 UTC, cacaocoffee commented on app/src/main/res/layout/activity_main.xml
> +        <FrameLayout
저 당연히 프래그먼트컨테이너 뷰로한줄알았는데 자동완성이 이렇게 무섭네요 감사합니다!

2024-04-30 06:47 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
> +        inputData()
네이밍이 항상어렵네요 감사합니다!

2024-04-30 06:47 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/ui/main/profile/MainProfileFragment.kt
> +    }
감사합니다! 덕분에 한번 더 돌아보게 되었네요!

2024-04-30 06:47 UTC, merged